[package]
name = "ppf-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "ppf_gui"
path = "src/main.rs"

[dependencies]
ppf-core.workspace = true
eframe.workspace = true
egui.workspace = true
rfd.workspace = true
image.workspace = true
md-5.workspace = true
sha1.workspace = true
crc32fast.workspace = true

[dev-dependencies]
tempfile.workspace = true
